name: loan_calculator
description: A new Flutter application.

publish_to: 'none'

version: 1.5.5+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.1
  url_launcher: ^6.0.9
  google_mobile_ads: ^1.0.0
  flutter_dotenv: ^5.0.0
  another_flushbar: ^1.10.24
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  share: ^2.0.4
  intl: ^0.17.0
  pdf: ^3.4.2
  package_info: ^2.0.2
  flutter_pdfview: ^1.2.1
  flutter_email_sender: ^5.0.2
  permission_handler: ^8.1.4+2
  path_provider: ^2.0.6
  shared_preferences: ^2.0.6
  cupertino_icons: ^1.0.0
  flutter_native_splash: ^1.2.1
  font_awesome_flutter: ^9.1.0
  screenshot: ^1.2.3
  device_info: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.1.0


flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
  fonts:
    - family: Audiowide
      fonts:
        - asset: fonts/Audiowide-Regular.ttf
flutter_native_splash:
  color: "#E3EBEC"
  image: assets/images/ic_launcher.png
  color_dark: "#212230"
  image_dark: assets/images/ic_launcher.png
  android_gravity: center
  fullscreen: true