// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:loan_calculator/models/history.dart';
import 'package:loan_calculator/models/mortgage_data.dart';
import 'package:loan_calculator/models/result_data.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(HistoryAdapter());
    registerAdapter(MortgageDataAdapter());
    registerAdapter(ResultDataAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(HistoryAdapter());
    registerAdapter(MortgageDataAdapter());
    registerAdapter(ResultDataAdapter());
  }
}
